In [1]:
####################################################################################################################
####################################################################################################################
############################################| PREPROCESSING |#######################################################
####################################################################################################################
####################################################################################################################

In [2]:
#import library
import pandas as pd
import numpy as np

file_komentar = "data_coba.csv"
file_normalisasi = "new_normalisasi.xlsx"
file_output_preprocessing = "pra_komentar.csv"

parameter_sentimen = "Sentimen"
parameter_komentar = "Komentar"

#membuka file komentar
komentar = pd.read_csv(file_komentar, error_bad_lines=False, delimiter=';', encoding='cp1252')
komentar.columns =['Nama', 'Komentar', 'Sentimen', 'Category','Time']

komentar['hasil_sentimen'] = komentar[parameter_sentimen]
komentar['hasil_komentar'] = komentar[parameter_komentar]
komentar.head(10)

Nama                                           Komentar  \
0               rere tv  Yg jadi masalah berikutnya anak2 sekampoong pd...   
1        muhammad ardhi  Yang salah tu yg nunjuk dia jadi mentri pendid...   
2       Cik Pelikelilik  Yang dilihat cuman yang di Kota, MAAF KITA YAN...   
3       MIXBOT OFFICIAL   YANG ADA PADA MABAR MAIN GAME KALO DI RUMAH MULU   
4  Adinda Rizky Aprilia  Ya Allah , semoga sekolahan mau melaksanakan k...   
5            Suseno Eno                   Untuk Tes Umptn gimana mas bro??   
6     Bang Yan Official  Tidak cocok jd mentri pendidikan....turun aja elo   
7    Arihana Khairunisa  Tidak adakah kompensasi untuk pembayaran spp u...   
8        muhammad amdad  Tidak Ada Wabah Selain Korupsi\nJadi untuk pen...   
9           Raif Umbara                                 this is not normal   

  Sentimen  Category                  Time hasil_sentimen  \
0  negatif       NaN  2020-11-07T22:41:20Z        negatif   
1  negatif       NaN  2020-10-13T02:34:15Z        negatif   
2  negatif       NaN  2020-09-28T05:54:36Z        negatif   
3  negatif       NaN  2020-09-24T03:30:55Z        negatif   
4  Negatif       NaN  2020-09-01T13:00:45Z        Negatif   
5  Negatif       NaN  2020-07-27T13:29:58Z        Negatif   
6  negatif       NaN  2020-07-21T15:48:58Z        negatif   
7  Negatif       NaN  2020-07-14T06:30:12Z        Negatif   
8  negatif       NaN  2020-07-13T17:00:32Z        negatif   
9  negatif       NaN  2020-11-02T03:24:03Z        negatif   

                                      hasil_komentar  
0  Yg jadi masalah berikutnya anak2 sekampoong pd...  
1  Yang salah tu yg nunjuk dia jadi mentri pendid...  
2  Yang dilihat cuman yang di Kota, MAAF KITA YAN...  
3   YANG ADA PADA MABAR MAIN GAME KALO DI RUMAH MULU  
4  Ya Allah , semoga sekolahan mau melaksanakan k...  
5                   Untuk Tes Umptn gimana mas bro??  
6  Tidak cocok jd mentri pendidikan....turun aja elo  
7  Tidak adakah kompensasi untuk pembayaran spp u...  
8  Tidak Ada Wabah Selain Korupsi\nJadi untuk pen...  
9                                 this is not normal

In [3]:
import string 
import re #regex library
import nltk
nltk.download('punkt')

from nltk import word_tokenize,sent_tokenize

# import word_tokenize dan FreqDist dari NLTK
from nltk.tokenize import word_tokenize 
from nltk.probability import FreqDist

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [4]:
# ------ Case Folding --------
def casefolding(text):
    text = text.lower()
    return text

In [5]:
#--------- PROSES TOKENIZING --------- 

def remove_special_char(text):
    #remove incomplete URL
    text = re.sub(r"http\S+", "", text)
    # change emoticon into their represented word
    #text = text.replace (':-)',"Emot-senyum").replace (':)',"Emot-senyum").text.replace ('(:',"Emot-senyum") .text.replace ('(-:',"Emot-senyum").text.replace ('^^', "Emot-senyum").text.replace ('^-^', "Emot-senyum").text.replace ('^_^',"Emot-senyum")
    # remove tab, new line, ans back slice
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # remove mention, link, hashtag
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())
    # remove non ASCII (simbols, chinese word, .etc)
    text = text.encode('ascii', 'replace').decode('ascii')
    # remove incomplete URL
    text = text.replace("http://", " ").replace("https://", " ")
    return text

#remove number
def remove_number(text):
    return  re.sub(r"\d+", "", text)

#remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans("","",string.punctuation))

#remove whitespace leading & trailing
def remove_whitespace_LT(text):
    return text.strip()

#remove multiple whitespace into single whitespace
def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text)

# remove single char
def remove_singl_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

# NLTK word rokenize 
def word_tokenize_wrapper(text):
    return word_tokenize(text)

# final function
# fungsi untuk resume semua fungsi tokenizing

def tokenizing(text):
    text = remove_special_char(text)
    text = remove_number(text)
    text = remove_punctuation(text)
    text = remove_whitespace_LT(text)
    text = remove_whitespace_multiple(text)
    text = remove_singl_char(text)
    text = word_tokenize_wrapper(text)
    return text


In [6]:
#fungsi gabungan tokenizing dan casefolding
def tokenizing_casefolding(text):
    text = casefolding(str(text))
    text = tokenizing(text)
    return text

In [7]:
komentar['tokenizing'] = komentar['hasil_komentar'].apply(tokenizing_casefolding)
komentar['tokenizing'].head(20)

0     [yg, jadi, masalah, berikutnya, anak, sekampoo...
1     [yang, salah, tu, yg, nunjuk, dia, jadi, mentr...
2     [yang, dilihat, cuman, yang, di, kota, maaf, k...
3     [yang, ada, pada, mabar, main, game, kalo, di,...
4     [ya, allah, semoga, sekolahan, mau, melaksanak...
5                 [untuk, tes, umptn, gimana, mas, bro]
6     [tidak, cocok, jd, mentri, pendidikanturun, aj...
7     [tidak, adakah, kompensasi, untuk, pembayaran,...
8     [tidak, ada, wabah, selain, korupsi, jadi, unt...
9                               [this, is, not, normal]
10    [the, real, krisis, pendidikan, banyak, anakan...
11                          [tatap, muka, di, rindukan]
12    [tai, lah, kantin, saya, di, kampus, sepi, gak...
13    [smk, swasta, bi, lek, gda, tugas, gda, materi...
14                                        [sialan, dah]
15    [serba, salah, emang, tapi, melihat, sitkon, p...
16    [semoga, situasi, cepat, amankarena, memang, p...
17    [semoga, covid, cepat, berakhir, dan, seko

In [8]:
komentar.head(10)

Nama                                           Komentar  \
0               rere tv  Yg jadi masalah berikutnya anak2 sekampoong pd...   
1        muhammad ardhi  Yang salah tu yg nunjuk dia jadi mentri pendid...   
2       Cik Pelikelilik  Yang dilihat cuman yang di Kota, MAAF KITA YAN...   
3       MIXBOT OFFICIAL   YANG ADA PADA MABAR MAIN GAME KALO DI RUMAH MULU   
4  Adinda Rizky Aprilia  Ya Allah , semoga sekolahan mau melaksanakan k...   
5            Suseno Eno                   Untuk Tes Umptn gimana mas bro??   
6     Bang Yan Official  Tidak cocok jd mentri pendidikan....turun aja elo   
7    Arihana Khairunisa  Tidak adakah kompensasi untuk pembayaran spp u...   
8        muhammad amdad  Tidak Ada Wabah Selain Korupsi\nJadi untuk pen...   
9           Raif Umbara                                 this is not normal   

  Sentimen  Category                  Time hasil_sentimen  \
0  negatif       NaN  2020-11-07T22:41:20Z        negatif   
1  negatif       NaN  2020-10-13T02:34:15Z        negatif   
2  negatif       NaN  2020-09-28T05:54:36Z        negatif   
3  negatif       NaN  2020-09-24T03:30:55Z        negatif   
4  Negatif       NaN  2020-09-01T13:00:45Z        Negatif   
5  Negatif       NaN  2020-07-27T13:29:58Z        Negatif   
6  negatif       NaN  2020-07-21T15:48:58Z        negatif   
7  Negatif       NaN  2020-07-14T06:30:12Z        Negatif   
8  negatif       NaN  2020-07-13T17:00:32Z        negatif   
9  negatif       NaN  2020-11-02T03:24:03Z        negatif   

                                      hasil_komentar  \
0  Yg jadi masalah berikutnya anak2 sekampoong pd...   
1  Yang salah tu yg nunjuk dia jadi mentri pendid...   
2  Yang dilihat cuman yang di Kota, MAAF KITA YAN...   
3   YANG ADA PADA MABAR MAIN GAME KALO DI RUMAH MULU   
4  Ya Allah , semoga sekolahan mau melaksanakan k...   
5                   Untuk Tes Umptn gimana mas bro??   
6  Tidak cocok jd mentri pendidikan....turun aja elo   
7  Tidak adakah kompensasi untuk pembayaran spp u...   
8  Tidak Ada Wabah Selain Korupsi\nJadi untuk pen...   
9                                 this is not normal   

                                          tokenizing  
0  [yg, jadi, masalah, berikutnya, anak, sekampoo...  
1  [yang, salah, tu, yg, nunjuk, dia, jadi, mentr...  
2  [yang, dilihat, cuman, yang, di, kota, maaf, k...  
3  [yang, ada, pada, mabar, main, game, kalo, di,...  
4  [ya, allah, semoga, sekolahan, mau, melaksanak...  
5              [untuk, tes, umptn, gimana, mas, bro]  
6  [tidak, cocok, jd, mentri, pendidikanturun, aj...  
7  [tidak, adakah, kompensasi, untuk, pembayaran,...  
8  [tidak, ada, wabah, selain, korupsi, jadi, unt...  
9                            [this, is, not, normal]

In [9]:
#normalisasi dan word handling
normalizad_word = pd.read_excel(file_normalisasi)

normalizad_word_dict = {}

for index, row in normalizad_word.iterrows():
    if row[0] not in normalizad_word_dict:
        normalizad_word_dict[row[0]] = row[1] 

def normalized_term(document):
    return [normalizad_word_dict[term] if term in normalizad_word_dict else term for term in document]

In [10]:
komentar['normalisasi'] = komentar['tokenizing'].apply(normalized_term)
komentar['normalisasi'].head(10)

0    [yang, jadi, masalah, berikutnya, anak, sekamp...
1    [yang, salah, itu, yang, nunjuk, dia, jadi, me...
2    [yang, dilihat, cuma, yang, di, kota, maaf, ki...
3    [yang, ada, pada, mabar, main, game, kalau, di...
4    [ya, allah, semoga, sekolahan, mau, melaksanak...
5                [untuk, tes, umptn, gimana, mas, bro]
6    [tidak, cocok, jadi, menteri, pendidikanturun,...
7    [tidak, adakah, kompensasi, untuk, pembayaran,...
8    [tidak, ada, wabah, selain, korupsi, jadi, unt...
9                              [this, is, not, normal]
Name: normalisasi, dtype: object

In [11]:
#----------- STOP WORD -----------

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
# get stopword indonesia
list_stopwords = stopwords.words('indonesian')

# append additional stopword
list_stopwords.extend(["yg", "dg", "rt", "dgn", "ny", "d", 'klo', 
                       'kalo', 'amp', 'biar', 'bikin', 'bilang', 
                       'gak', 'ga', 'krn', 'nya', 'nih', 'sih', 
                       'si', 'tau', 'tdk', 'tuh', 'utk', 'ya', 
                       'jd', 'jgn', 'sdh', 'aja', 'n', 't', 
                       'nyg', 'hehe', 'pen', 'u', 'nan', 'loh', 'rt',
                       '&amp', 'yah','yth'])

# ----------------------- add stopword from txt file ------------------------------------
# read txt stopword using pandas
txt_stopword = pd.read_csv("stopword.csv", names= ["stopwords"])

# convert stopword string to list & append additional stopword
list_stopwords.extend(txt_stopword["stopwords"][0].split(' '))

# convert list to dictionary
list_stopwords = set(list_stopwords)


#remove stopword pada list token
def stopwords_removal(words):
    return [word for word in words if word not in list_stopwords]


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [12]:
komentar['stopword'] = komentar['normalisasi'].apply(stopwords_removal)
komentar['stopword'].head(10)

0    [anak, sekampoong, pd, tidoor, mas, jam, ato, ...
1    [salah, nunjuk, menteri, pendidikangak, pengal...
2    [kota, maaf, didesa, lihat, ambil, sample, nia...
3                     [mabar, main, game, rumah, mulu]
4    [allah, semoga, sekolahan, melaksanakan, kurik...
5                       [tes, umptn, gimana, mas, bro]
6               [cocok, menteri, pendidikanturun, elo]
7    [adakah, kompensasi, pembayaran, spp, sekolah,...
8    [wabah, korupsi, pendidikan, mending, tatap, m...
9                              [this, is, not, normal]
Name: stopword, dtype: object

In [13]:
# import Sastrawi package
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import swifter

# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# stemmed
def stemmed_wrapper(term):
    return stemmer.stem(term)

term_dict = {}
for document in komentar['stopword']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '
for term in term_dict:
    term_dict[term] = stemmed_wrapper(str(term))
    print(term,":" ,term_dict[term])

def get_stemmed_term(document):
    return [term_dict[term] for term in document]

anak : anak
sekampoong : sekampoong
pd : pd
tidoor : tidoor
mas : mas
jam : jam
ato : ato
malem : malem
tidorrr : tidorrr
tk : tk
tidur : tidur
kegiatan : giat
mikirrr : mikirrr
belajar : ajar
gimana : gimana
saranin : saranin
larii : lari
main : main
olah : olah
raga : raga
bosyenn : bosyenn
gw : gw
tua : tua
capek : capek
susahh : susahh
apalgi : apalgi
binguung : binguung
deh : deh
suruh : suruh
ngapain : ngapain
salah : salah
nunjuk : nunjuk
menteri : menteri
pendidikangak : pendidikangak
pengalaman : alam
ilmu : ilmu
mumpuni : mumpuni
pendidikan : didik
berat : berat
orang : orang
pengalamanatau : pengalamanatau
berkecimpung : kecimpung
bidang : bidang
cocok : cocok
perhubungan : hubung
semacamnya : macam
kota : kota
maaf : maaf
didesa : desa
lihat : lihat
ambil : ambil
sample : sample
niat : niat
mabar : mabar
game : game
rumah : rumah
mulu : mulu
allah : allah
semoga : moga
sekolahan : sekolah
melaksanakan : laksana
kurikulum : kurikulum
darurat : darurat
dianjurkan : anjur
keme

ankank : ankank
sllu : sllu
mngeluh : mngeluh
dskolah : dskolah
td : td
prnh : prnh
mnjlskn : mnjlskn
materimsuk : materimsuk
kls : kls
srh : srh
krjain : krjain
tgasbgaimana : tgasbgaimana
ankbs : ankbs
mngerti : mngerti
dn : dn
phm : phm
ttng : ttng
pljaran : pljaran
mteri : mteri
pjj : pjj
tnpa : tnpa
djlsin : djlsin
ngsal : ngsal
sruh : sruh
lsng : lsng
ngsih : ngsih
tgas : tgas
sngt : sngt
bnarmnjdi : bnarmnjdi
msalah : msalah
sriusmsak : sriusmsak
ankhrs : ankhrs
nanya : nanya
gogelapalah : gogelapalah
arti : arti
slma : slma
thnank : thnank
tmbh : tmbh
ngandelin : ngandelin
les : les
luartolong : luartolong
pakditinjau : pakditinjau
kmbali : kmbali
guruskrngwlaupun : guruskrngwlaupun
diluar : luar
thapakh : thapakh
sprti : sprti
anksy : anksy
almi : almi
initrimksih : initrimksih
nadiem : nadiem
ush : ush
diskus : diskus
mendikbud : mendikbud
coba : coba
discuss : discuss
nu : nu
muhammadiyah : muhammadiyah
cari : cari
pakar : pakar
musywarah : musywarah
mufakkat : mufakkat
coba

dapet : dapet
jajan : jajan
hehehe : hehehe
keluarlah : keluar
bos : bos
lht : lht
ad : ad
mati : mati
kejang : kejang
karnd : karnd
ijinkan : ijinkan
waras : waras
kah : kah
njirr : njirr
liatin : liatin
layar : layar
laptop : laptop
minus : minus
bnar : bnar
stressdan : stressdan
sbgai : sbgai
gru : gru
mlihat : mlihat
ankorg : ankorg
ptus : ptus
asa : asa
optimal : optimal
makassar : makassar
manusia : manusia
didunia : dunia
mmg : mmg
smakin : smakin
mmkirkan : mmkirkan
nasib : nasib
kluarga : kluarga
mnggantikan : mnggantikan
membimbing : bimbing
mrk : mrk
bljar : bljar
ekstra : ekstra
sabar : sabar
sehrsnya : sehrsnya
disesuaikn : disesuaikn
disamakan : sama
trlalu : trlalu
mmberatkn : mmberatkn
jarang : jarang
kulah : kulah
seminggu : minggu
ajh : ajh
kdang : kdang
malam : malam
unlimited : unlimited
cma : cma
smpai : smpai
sore : sore
normalberat : normalberat
beben : beben
awas : awas
tiktok : tiktok
ngomong : ngomong
ajaemang : ajaemang
ente : ente
nanggung : nanggung
kuotany

relaxasi : relaxasi
protokoler : protokoler
khawatiran : khawatir
berbaur : baur
dibayangkan : bayang
bonding : bonding
suasana : suasana
dirasakan : rasa
merasakan : rasa
bdr : bdr
itupun : itu
berkenan : kenan
baiknya : baik
observasi : observasi
penjajakan : jaja
terkait : kait
jenjang : jenjang
lembaga : lembaga
menyimak : simak
lekas : lekas
diskolah : disko
dikarantina : karantina
melangkah : lang
benahin : benahin
tertinggal : tinggal
rusak : rusak
sejahterakan : sejahtera
terpencil : pencil
jakarta : jakarta
sejahtera : sejahtera
terstruktur : struktur
basmi : basmi
akarakarnya : akarakarnya
menyalahgunakan : menyalahgunakan
bop : bop
modusnya : modus
ditransfer : transfer
but : but
end : end
menyetorkan : setor
recehan : receh
habiskan : habis
pns : pns
senior : senior
mager : mager
senang : senang
kongkow : kongkow
kantor : kantor
ngekos : ngekos
kabar : kabar
byr : byr
nominal : nominal
lumayan : lumayan
menunggak : tunggak
pembngunan : pembngunan
agree : agree
statement : s

mentrikami : mentrikami
diambil : ambil
ri : ri
melindungi : lindung
terhindar : hindar
klaster : klaster
manfaat : manfaat
berkah : berkah
robbal : robbal
alamiin : alamiin
menimbulkan : timbul
akibat : akibat
disalahkan : salah
siaran : siar
televisi : televisi
nasional : nasional
menayangkan : tayang
kabel : kabel
berbayar : bayar
memilikinya : milik
menggandeng : gandeng
wishnutama : wishnutama
erick : erick
thohir : thohir
mewujudkan : wujud
konten : konten
berkualitas : kualitas
melulu : melulu
sinetron : sinetron
isinya : isi
pertengkaran : tengkar
perceraian : cerai
pamer : pamer
harta : harta
perkembangan : kembang
amin : amin
pemikiran : pikir
mengharapkan : harap
sepengetahuan : tahu
hancurkan : hancur
terpenting : penting
skg : skg
disosialisikan : disosialisikan
sekeluarga : keluarga
care : care
menganggap : anggap
memandang : pandang
marilah : mari
ikuti : ikut
menjaga : jaga
mari : mari
berdoa : doa
lembutselalu : lembutselalu
berbicara : bicara
positivehehehesukses : po

azka : azka
dedi : dedi
jawa : jawa
timur : timur
waswas : waswas
covidpun : covidpun
terpendamnya : pendam
melek : melek
permanen : permanen
sekelas : kelas
finlandia : finlandia
speed : speed
kenceng : kenceng
nasabiaya : nasabiaya
murahsarana : murahsarana
prasarana : prasarana
medsos : medsos
sapa : sapa
doakan : doa
komplain : komplain
liburkan : libur
ketidaknyamanan : ketidaknyamanan
sempit : sempit
kesalahan : salah
tunggu : tunggu
korban : korban
bertindak : tindak
positif : positif
sudut : sudut
hambatan : hambat
rintangan : rintang
bandingkan : banding
save : save
jiwa : jiwa
binar : binar
matanya : mata
betu : betu
tvri : tvri
menarik : tarik
menyesuakan : sua
acaranya : acara
membidik : bidik
penontonya : penontonya
bersahaja : sahaja
lanjutkan : lanjut
amburadul : amburadul
disaat : saat
menjabat : jabat
nemu : nemu
kerasa : rasa
ngejabat : ngejabat
ancuran : ancuran
yuk : yuk
mengeluhnya : keluh
udha : udha
paaaakkk : paaaakkk
diangkat : angkat
disulitkan : sulit
keadaan

In [14]:
komentar['stemmed'] = komentar['stopword'].swifter.apply(get_stemmed_term)

In [15]:
komentar['stemmed'].head(20)

0     [anak, sekampoong, pd, tidoor, mas, jam, ato, ...
1     [salah, nunjuk, menteri, pendidikangak, alam, ...
2     [kota, maaf, desa, lihat, ambil, sample, niat,...
3                      [mabar, main, game, rumah, mulu]
4     [allah, moga, sekolah, laksana, kurikulum, dar...
5                        [tes, umptn, gimana, mas, bro]
6                [cocok, menteri, pendidikanturun, elo]
7     [ada, kompensasi, bayar, spp, sekolah, swasta,...
8     [wabah, korupsi, didik, mending, tatap, muka, ...
9                               [this, is, not, normal]
10    [the, real, krisis, didik, anakanak, era, gara...
11                                 [tatap, muka, rindu]
12    [tai, kantin, kampus, sepi, pemasukanpercuma, ...
13    [smk, swasta, bi, lek, gda, tugas, gda, materi...
14                                               [sial]
15    [serba, salah, emang, sitkon, gera, mahasiswa,...
16    [moga, situasi, cepat, amankarena, didik, pjjs...
17    [moga, covid, cepat, sekolah, ajar, ajar, 

In [16]:
#convert preprocessing to text
def list2string(list):
    text = ' '.join(list)
    return text
 
komentar['preprocessing'] = komentar['stemmed'].apply(list2string)

In [17]:
komentar['preprocessing'].head(20)
komentar.to_csv(file_output_preprocessing)

In [18]:
####################################################################################################################
####################################################################################################################
##########################################| SENTIMEN ANALYSIS |#####################################################
####################################################################################################################
####################################################################################################################

In [19]:
#Persiapan training data

from collections import Counter
import csv

komentar = pd.read_csv("pra_komentar.csv")

komentar.head(10)


Unnamed: 0                  Nama  \
0           0               rere tv   
1           1        muhammad ardhi   
2           2       Cik Pelikelilik   
3           3       MIXBOT OFFICIAL   
4           4  Adinda Rizky Aprilia   
5           5            Suseno Eno   
6           6     Bang Yan Official   
7           7    Arihana Khairunisa   
8           8        muhammad amdad   
9           9           Raif Umbara   

                                            Komentar Sentimen  Category  \
0  Yg jadi masalah berikutnya anak2 sekampoong pd...  negatif       NaN   
1  Yang salah tu yg nunjuk dia jadi mentri pendid...  negatif       NaN   
2  Yang dilihat cuman yang di Kota, MAAF KITA YAN...  negatif       NaN   
3   YANG ADA PADA MABAR MAIN GAME KALO DI RUMAH MULU  negatif       NaN   
4  Ya Allah , semoga sekolahan mau melaksanakan k...  Negatif       NaN   
5                   Untuk Tes Umptn gimana mas bro??  Negatif       NaN   
6  Tidak cocok jd mentri pendidikan....turun aja elo  negatif       NaN   
7  Tidak adakah kompensasi untuk pembayaran spp u...  Negatif       NaN   
8  Tidak Ada Wabah Selain Korupsi\nJadi untuk pen...  negatif       NaN   
9                                 this is not normal  negatif       NaN   

                   Time hasil_sentimen  \
0  2020-11-07T22:41:20Z        negatif   
1  2020-10-13T02:34:15Z        negatif   
2  2020-09-28T05:54:36Z        negatif   
3  2020-09-24T03:30:55Z        negatif   
4  2020-09-01T13:00:45Z        Negatif   
5  2020-07-27T13:29:58Z        Negatif   
6  2020-07-21T15:48:58Z        negatif   
7  2020-07-14T06:30:12Z        Negatif   
8  2020-07-13T17:00:32Z        negatif   
9  2020-11-02T03:24:03Z        negatif   

                                      hasil_komentar  \
0  Yg jadi masalah berikutnya anak2 sekampoong pd...   
1  Yang salah tu yg nunjuk dia jadi mentri pendid...   
2  Yang dilihat cuman yang di Kota, MAAF KITA YAN...   
3   YANG ADA PADA MABAR MAIN GAME KALO DI RUMAH MULU   
4  Ya Allah , semoga sekolahan mau melaksanakan k...   
5                   Untuk Tes Umptn gimana mas bro??   
6  Tidak cocok jd mentri pendidikan....turun aja elo   
7  Tidak adakah kompensasi untuk pembayaran spp u...   
8  Tidak Ada Wabah Selain Korupsi\nJadi untuk pen...   
9                                 this is not normal   

                                          tokenizing  \
0  ['yg', 'jadi', 'masalah', 'berikutnya', 'anak'...   
1  ['yang', 'salah', 'tu', 'yg', 'nunjuk', 'dia',...   
2  ['yang', 'dilihat', 'cuman', 'yang', 'di', 'ko...   
3  ['yang', 'ada', 'pada', 'mabar', 'main', 'game...   
4  ['ya', 'allah', 'semoga', 'sekolahan', 'mau', ...   
5  ['untuk', 'tes', 'umptn', 'gimana', 'mas', 'bro']   
6  ['tidak', 'cocok', 'jd', 'mentri', 'pendidikan...   
7  ['tidak', 'adakah', 'kompensasi', 'untuk', 'pe...   
8  ['tidak', 'ada', 'wabah', 'selain', 'korupsi',...   
9                    ['this', 'is', 'not', 'normal']   

                                         normalisasi  \
0  ['yang', 'jadi', 'masalah', 'berikutnya', 'ana...   
1  ['yang', 'salah', 'itu', 'yang', 'nunjuk', 'di...   
2  ['yang', 'dilihat', 'cuma', 'yang', 'di', 'kot...   
3  ['yang', 'ada', 'pada', 'mabar', 'main', 'game...   
4  ['ya', 'allah', 'semoga', 'sekolahan', 'mau', ...   
5  ['untuk', 'tes', 'umptn', 'gimana', 'mas', 'bro']   
6  ['tidak', 'cocok', 'jadi', 'menteri', 'pendidi...   
7  ['tidak', 'adakah', 'kompensasi', 'untuk', 'pe...   
8  ['tidak', 'ada', 'wabah', 'selain', 'korupsi',...   
9                    ['this', 'is', 'not', 'normal']   

                                            stopword  \
0  ['anak', 'sekampoong', 'pd', 'tidoor', 'mas', ...   
1  ['salah', 'nunjuk', 'menteri', 'pendidikangak'...   
2  ['kota', 'maaf', 'didesa', 'lihat', 'ambil', '...   
3         ['mabar', 'main', 'game', 'rumah', 'mulu']   
4  ['allah', 'semoga', 'sekolahan', 'melaksanakan...   
5           ['tes', 'umptn', 'gimana', 'mas', 'bro']   
6     ['cocok', 'menteri', 'pendidikantur

In [55]:
#Persiapan training data

from collections import Counter
import csv

komentar = pd.read_csv("pra_komentar.csv")

komentar.head(10)

label = komentar['Sentimen'].to_list()
label = [str(perlabel).lower().replace(" ","") for perlabel in label] # to lower case


data_text = komentar['preprocessing'].to_list()

In [56]:
# import nltk
# nltk.download()


#proses TFIDF
# from sklearn.feature_extraction.text import TfidfVectorizer  
# tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7)  
# X = tfidfconverter.fit_transform(data_text).toarray()

In [57]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(data_text, label, test_size=0.2, random_state=123)

#Keterangan jumlah data training dan data uji
print("Data training:")
print(len(X_train))
print(Counter(y_train))
 
print("Data testing:")
print(len(X_test))
print(Counter(y_test))

Data training:
327
Counter({'positif': 161, 'netral': 83, 'negatif': 83})
Data testing:
82
Counter({'positif': 39, 'negatif': 24, 'netral': 19})


In [23]:
#%%
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [58]:
#kernel_type = linear, poly, rbf, sigmoid
#Proses tfidf

def fungsiSVM(jenis_kernel):
    text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('svc', SVC(kernel=jenis_kernel,gamma='auto'))])
#     return Pipeline([('scaler', StandardScaler()), ('svc', SVC(kernel=jenis_kernel,gamma='auto'))])
    return text_clf

In [59]:
X_test

['tatap muka rindu',
 'muda anak umur masuk tk sekolah daring susah susah hati anak butuh temu guru anak butuh temu teman anak segan ajar gurulebih percaya ajar guru',
 'capek liatin layar laptop minus mata nambah',
 'nadiem makarim covid menteri suka bocil nadiem makarim covid menteri benci bocil',
 'tuju bijak menteri moga pandemi covid sabar ikhlas',
 'smk swasta bi lek gda tugas gda materi tetepp bayar slurrrrr',
 'nadiem ush diskus mendikbud negeri coba discuss nu muhammadiyah cari solusi pakar didik negeri musywarah mufakkat coba conference press masyarakat kampus nyata lapang rumit ekonomi mikro carut marut revolusi mncerdaskan hidup bangsa dipertimbngkn trlebih support nadiem terima kasih wasslm wr wb',
 'keren mah nadiem legowo terima kritik program untuku goodjob',
 'pribadi respect menteri mendikbud protes mahasiswa demo bro this for indonesia coba pikir jernih rap persen menteri aku salah menteri berani jujur publik respect menteri laku baik putraputri bangsa',
 'serba sala

In [60]:
#kernel POLY
kernel_poly = fungsiSVM('poly')
kernel_poly.fit(X_train, y_train)
prediction_kernel_poly = kernel_poly.predict(X_test)

#menghitung akurasi dengan confusion matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,prediction_kernel_poly))
print(classification_report(y_test,prediction_kernel_poly))
print(accuracy_score(y_test, prediction_kernel_poly))

[[ 0  0 24]
 [ 0  0 19]
 [ 0  0 39]]
              precision    recall  f1-score   support

     negatif       0.00      0.00      0.00        24
      netral       0.00      0.00      0.00        19
     positif       0.48      1.00      0.64        39

    accuracy                           0.48        82
   macro avg       0.16      0.33      0.21        82
weighted avg       0.23      0.48      0.31        82

0.47560975609756095


C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [61]:
#kernel LINEAR
kernel_linear = fungsiSVM('linear')
kernel_linear.fit(X_train, y_train)
prediction_kernel_linear = kernel_linear.predict(X_test)

#menghitung akurasi dengan confusion matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,prediction_kernel_linear))
print(classification_report(y_test,prediction_kernel_linear))
print(accuracy_score(y_test, prediction_kernel_linear))

[[14  4  6]
 [ 4  8  7]
 [ 1  1 37]]
              precision    recall  f1-score   support

     negatif       0.74      0.58      0.65        24
      netral       0.62      0.42      0.50        19
     positif       0.74      0.95      0.83        39

    accuracy                           0.72        82
   macro avg       0.70      0.65      0.66        82
weighted avg       0.71      0.72      0.70        82

0.7195121951219512


In [62]:
#kernel rbf
kernel_rbf = fungsiSVM('rbf')
kernel_rbf.fit(X_train, y_train)
prediction_kernel_rbf = kernel_rbf.predict(X_test)

#menghitung akurasi dengan confusion matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,prediction_kernel_rbf))
print(classification_report(y_test,prediction_kernel_rbf))
print(accuracy_score(y_test, prediction_kernel_rbf))

[[ 0  0 24]
 [ 0  0 19]
 [ 0  0 39]]
              precision    recall  f1-score   support

     negatif       0.00      0.00      0.00        24
      netral       0.00      0.00      0.00        19
     positif       0.48      1.00      0.64        39

    accuracy                           0.48        82
   macro avg       0.16      0.33      0.21        82
weighted avg       0.23      0.48      0.31        82

0.47560975609756095


In [63]:
#kernel sigmoid
kernel_sigmoid = fungsiSVM('sigmoid')
kernel_sigmoid.fit(X_train, y_train)
prediction_kernel_sigmoid = kernel_sigmoid.predict(X_test)

#menghitung akurasi dengan confusion matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,prediction_kernel_sigmoid))
print(classification_report(y_test,prediction_kernel_sigmoid))
print(accuracy_score(y_test, prediction_kernel_sigmoid))

[[ 0  0 24]
 [ 0  0 19]
 [ 0  0 39]]
              precision    recall  f1-score   support

     negatif       0.00      0.00      0.00        24
      netral       0.00      0.00      0.00        19
     positif       0.48      1.00      0.64        39

    accuracy                           0.48        82
   macro avg       0.16      0.33      0.21        82
weighted avg       0.23      0.48      0.31        82

0.47560975609756095


In [64]:
####################################################################################################################
####################################################################################################################
############################################| pengujian |#######################################################
####################################################################################################################
####################################################################################################################

In [65]:
pengujian = pd.read_csv("data_testing.csv", delimiter=';', encoding='cp1252')
pengujian.head(10)

sentimen
0  Yang paling penting dalam pendidikan kita adal...
1  Yak betul mas menteri, psikososialnya Anak-ana...
2  Pak Nadiem vulgar minta maaf karena sudah keba...
3  mentri diktator, mentri gak mau dengar keluhan...
4   mentri cerdas, namun tidak dengan SDM dibawahnya
5  Mereka cuma bahas soal pendidikan anak yg puny...
6  Merasa aman bngt anjir punya mentri pendidikan...
7  Menyalahkan keadaan juga faktor penghambat kem...
8  Menut saya kalo pelosok desa bebas sekolah jad...
9  Menurutku bukan brrti selama kepemimpinan beli...

In [66]:
pengujian['tokenizing'] = pengujian['sentimen'].apply(tokenizing_casefolding)
pengujian['normalisasi'] = pengujian['tokenizing'].apply(normalized_term)
pengujian['stopword'] = pengujian['normalisasi'].apply(stopwords_removal)

for document in pengujian['stopword']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '
for term in term_dict:
    term_dict[term] = stemmed_wrapper(str(term))
#     print(term,":" ,term_dict[term])

def get_stemmed_term(document):
    return [term_dict[term] for term in document]

pengujian['stemmed'] = pengujian['stopword'].swifter.apply(get_stemmed_term)
pengujian['preprocessing'] = pengujian['stemmed'].apply(list2string)

In [67]:
pengujian.head(10)

sentimen  \
0  Yang paling penting dalam pendidikan kita adal...   
1  Yak betul mas menteri, psikososialnya Anak-ana...   
2  Pak Nadiem vulgar minta maaf karena sudah keba...   
3  mentri diktator, mentri gak mau dengar keluhan...   
4   mentri cerdas, namun tidak dengan SDM dibawahnya   
5  Mereka cuma bahas soal pendidikan anak yg puny...   
6  Merasa aman bngt anjir punya mentri pendidikan...   
7  Menyalahkan keadaan juga faktor penghambat kem...   
8  Menut saya kalo pelosok desa bebas sekolah jad...   
9  Menurutku bukan brrti selama kepemimpinan beli...   

                                          tokenizing  \
0  [yang, paling, penting, dalam, pendidikan, kit...   
1  [yak, betul, mas, menteri, psikososialnya, ana...   
2  [pak, nadiem, vulgar, minta, maaf, karena, sud...   
3  [mentri, diktator, mentri, gak, mau, dengar, k...   
4  [mentri, cerdas, namun, tidak, dengan, sdm, di...   
5  [mereka, cuma, bahas, soal, pendidikan, anak, ...   
6  [merasa, aman, bngt, anjir, punya, mentri, pen...   
7  [menyalahkan, keadaan, juga, faktor, penghamba...   
8  [menut, saya, kalo, pelosok, desa, bebas, seko...   
9  [menurutku, bukan, brrti, selama, kepemimpinan...   

                                         normalisasi  \
0  [yang, paling, penting, dalam, pendidikan, kit...   
1  [yak, betul, mas, menteri, psikososialnya, ana...   
2  [pak, nadiem, vulgar, minta, maaf, karena, sud...   
3  [menteri, diktator, menteri, tidak, mau, denga...   
4  [menteri, cerdas, namun, tidak, dengan, sdm, d...   
5  [mereka, cuma, bahas, soal, pendidikan, anak, ...   
6  [merasa, aman, banget, anjir, punya, menteri, ...   
7  [menyalahkan, keadaan, juga, faktor, penghamba...   
8  [menut, saya, kalau, pelosok, desa, bebas, sek...   
9  [menurutku, bukan, berarti, selama, kepemimpin...   

                                            stopword  \
0  [pendidikan, membentuk, moral, siswa, akhlaqny...   
1  [yak, mas, menteri, psikososialnya, anakanak, ...   
2  [nadiem, vulgar, maaf, kebawa, budaya, kampusn...   
3  [menteri, diktator, menteri, dengar, keluhan, ...   
4                 [menteri, cerdas, sdm, dibawahnya]   
5  [bahas, pendidikan, anak, fasilitas, bayangkan...   
6  [aman, banget, anjir, menteri, pendidikan, om,...   
7        [menyalahkan, faktor, penghambat, kemajuan]   
8  [menut, pelosok, desa, bebas, sekolah, gx, beb...   
9    [menurutku, kepemimpinan, beliau, salah, bener]   

                                             stemmed  \
0  [didik, bentuk, moral, siswa, akhlaqnya, attit...   
1  [yak, mas, menteri, psikososialnya, anakanak, ...   
2  [nadiem, vulgar, maaf, bawa, budaya, kampus, m...   
3  [menteri, diktator, menteri, dengar, keluh, wa...   
4                      [menteri, cerdas, sdm, bawah]   
5  [bahas, didik, anak, fasilitas, bayang, anak, ...   
6  [aman, banget, anjir, menteri, didik, om, nadiem]   
7                      [salah, faktor, hambat, maju]   
8  [menut, pelosok, desa, bebas, sekolah, gx, beb...   
9              [turut, pimpin, beliau, salah, bener]   

                                       preprocessing  
0  didik bentuk moral siswa akhlaqnya attitudenya...  
1  yak mas menteri psikososialnya anakanak kasi r...  
2  nadiem vulgar maaf bawa budaya kampus maaf sal...  
3  menteri diktator menteri dengar keluh wali mur...  
4                           menteri cerdas sdm bawah  
5  bahas didik anak fasilitas bayang anak desa pe...  
6          aman banget anjir menteri didik om nadiem  
7                           salah faktor hambat maju  
8  menut pelosok desa bebas sekolah gx beban ekon...  
9                    turut pimpin beliau salah bener

In [78]:
data_text_pengujian = pengujian['preprocessing'].to_list()

# tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7)  
# tf_idf_data_pengujian = tfidfconverter.fit_transform(data_text_pengujian).toarray()

In [82]:
#kernel_type = poly, linear, rbf, sigmoid

kernel_poly.predict(data_text_pengujian)
pengujian['poly'] = kernel_poly.predict(data_text_pengujian)

kernel_linear.predict(data_text_pengujian)
pengujian['linear'] = kernel_linear.predict(data_text_pengujian)

kernel_rbf.predict(data_text_pengujian)
pengujian['rbf'] = kernel_rbf.predict(data_text_pengujian)

kernel_sigmoid.predict(data_text_pengujian)
pengujian['sigmoid'] = kernel_sigmoid.predict(data_text_pengujian)

pengujian.head(10)

sentimen  \
0  Yang paling penting dalam pendidikan kita adal...   
1  Yak betul mas menteri, psikososialnya Anak-ana...   
2  Pak Nadiem vulgar minta maaf karena sudah keba...   
3  mentri diktator, mentri gak mau dengar keluhan...   
4   mentri cerdas, namun tidak dengan SDM dibawahnya   
5  Mereka cuma bahas soal pendidikan anak yg puny...   
6  Merasa aman bngt anjir punya mentri pendidikan...   
7  Menyalahkan keadaan juga faktor penghambat kem...   
8  Menut saya kalo pelosok desa bebas sekolah jad...   
9  Menurutku bukan brrti selama kepemimpinan beli...   

                                          tokenizing  \
0  [yang, paling, penting, dalam, pendidikan, kit...   
1  [yak, betul, mas, menteri, psikososialnya, ana...   
2  [pak, nadiem, vulgar, minta, maaf, karena, sud...   
3  [mentri, diktator, mentri, gak, mau, dengar, k...   
4  [mentri, cerdas, namun, tidak, dengan, sdm, di...   
5  [mereka, cuma, bahas, soal, pendidikan, anak, ...   
6  [merasa, aman, bngt, anjir, punya, mentri, pen...   
7  [menyalahkan, keadaan, juga, faktor, penghamba...   
8  [menut, saya, kalo, pelosok, desa, bebas, seko...   
9  [menurutku, bukan, brrti, selama, kepemimpinan...   

                                         normalisasi  \
0  [yang, paling, penting, dalam, pendidikan, kit...   
1  [yak, betul, mas, menteri, psikososialnya, ana...   
2  [pak, nadiem, vulgar, minta, maaf, karena, sud...   
3  [menteri, diktator, menteri, tidak, mau, denga...   
4  [menteri, cerdas, namun, tidak, dengan, sdm, d...   
5  [mereka, cuma, bahas, soal, pendidikan, anak, ...   
6  [merasa, aman, banget, anjir, punya, menteri, ...   
7  [menyalahkan, keadaan, juga, faktor, penghamba...   
8  [menut, saya, kalau, pelosok, desa, bebas, sek...   
9  [menurutku, bukan, berarti, selama, kepemimpin...   

                                            stopword  \
0  [pendidikan, membentuk, moral, siswa, akhlaqny...   
1  [yak, mas, menteri, psikososialnya, anakanak, ...   
2  [nadiem, vulgar, maaf, kebawa, budaya, kampusn...   
3  [menteri, diktator, menteri, dengar, keluhan, ...   
4                 [menteri, cerdas, sdm, dibawahnya]   
5  [bahas, pendidikan, anak, fasilitas, bayangkan...   
6  [aman, banget, anjir, menteri, pendidikan, om,...   
7        [menyalahkan, faktor, penghambat, kemajuan]   
8  [menut, pelosok, desa, bebas, sekolah, gx, beb...   
9    [menurutku, kepemimpinan, beliau, salah, bener]   

                                             stemmed  \
0  [didik, bentuk, moral, siswa, akhlaqnya, attit...   
1  [yak, mas, menteri, psikososialnya, anakanak, ...   
2  [nadiem, vulgar, maaf, bawa, budaya, kampus, m...   
3  [menteri, diktator, menteri, dengar, keluh, wa...   
4                      [menteri, cerdas, sdm, bawah]   
5  [bahas, didik, anak, fasilitas, bayang, anak, ...   
6  [aman, banget, anjir, menteri, didik, om, nadiem]   
7                      [salah, faktor, hambat, maju]   
8  [menut, pelosok, desa, bebas, sekolah, gx, beb...   
9              [turut, pimpin, beliau, salah, bener]   

                                       preprocessing  sigmoid     poly  \
0  didik bentuk moral siswa akhlaqnya attitudenya...  positif  positif   
1  yak mas menteri psikososialnya anakanak kasi r...  positif  positif   
2  nadiem vulgar maaf bawa budaya kampus maaf sal...  positif  positif   
3  menteri diktator menteri dengar keluh wali mur...  positif  positif   
4                           menteri cerdas sdm bawah  positif  positif   
5  bahas didik anak fasilitas bayang anak desa pe...  positif  positif   
6          aman banget anjir menteri didik om nadiem  positif  positif   
7                           salah faktor hambat maju  positif  positif   
8  menut pelosok desa bebas sekolah gx beban ekon...  positif  positif   
9                    turut pimpin beliau salah bener  positif  positif   

    linear      rbf  
0  negatif  positif  
1  positif  positif  
2  positif  positif  
3  negatif  positif  
4  positif  positif  
5  negatif  